blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls'))
]

blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('titles/', views.titles, name='titles'),
    path('titles/<int:title_id>/', views.title, name='title'),
]

blogs/models.py
from django.db import models

# Create your models here.


class Title(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text


class Description(models.Model):
    topic = models.ForeignKey(Title, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Descriptions'

    def __str__(self):
        return f"{self.text[:50]}"

blogs/views.py
from django.shortcuts import render
from .models import Title
# Create your views here.


def index(request):
    return render(request, 'blogs/index.html')


def titles(request):
    titles = Title.objects.order_by('date_added')
    context = {'titles': titles}
    return render(request, 'blogs/titles.html', context)


def title(request, title_id):
    title = Title.objects.get(id=title_id)
    descriptions = title.description_set.order_by('-date_added')
    context = {'title': title, 'descriptions': descriptions}
    return render(request, 'blogs/title.html', context)

blogs/templates/blogs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Blog!!</title>
</head>
<body>
<p>
<a href="{% url 'blogs:index' %}">Django Blog!!</a> -
<a href="{% url 'blogs:titles' %}">Topics</a>
</p>
{% block content %}{% endblock content %}
</body>
</html>

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% block content %}
<h1>
    This Blog is implemented Using Django Framework by Python
</h1>
{% endblock content %}

blogs/templates/blogs/title.html
{% extends 'blogs/base.html' %}
{% block content %}
<p>Topic: {{ title }}</p>
 <p>Entries:</p>
<ul>
{% for description in descriptions %}
 <li>
<p>{{ description.date_added|date:'M d, Y H:i' }}</p>
<p>{{ description.text|linebreaks }}</p>
 </li>
{% empty %}
 <li>There are no entries for this topic yet.</li>
 {% endfor %}
 </ul>
{% endblock content %}

blogs/templates/blogs/titles.html
{% extends "blogs/base.html" %}
{% block content %}
 <h>Titles</h>
<ul>
{% for title in titles %}
    <li>
 <a href="{% url 'blogs:title' title.id %}">{{ title }}</a>
 </li>
{% empty %}
 <li>No topics have been added yet.</li>
{% endfor %}
</ul>
{% endblock content %}